name: Push Docker Image to ACR

on:
  push:
    branches:
      - master  # Trigger workflow on push to master branch

jobs:
  push-to-acr:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Azure login using Service Principal credentials
      - name: Set up Azure login
        uses: azure/login@v1
        with:
          creds: '{"clientId": "${{ secrets.AZURE_CLIENT_ID }}", "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}", "tenantId": "${{ secrets.AZURE_TENANT_ID }}", "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"}'

      # Step 3: Log in to Azure Container Registry (ACR)
      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      # Step 4: Build, Tag, and Push Docker Image to ACR
      - name: Build, Tag, and Push Docker Image
        run: |
          docker build -t dockerized_image_demo .
          docker tag dockerized_image_demo:latest ${{ secrets.ACR_NAME }}.azurecr.io/ayeman/poc:latest
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/ayeman/poc:latest
