name: Upload Template to S3

on:
  push:
    branches:
      - master  # Trigger the action when pushing to master branch

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up AWS credentials using OIDC
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  
        aws-region: ap-south-1  

    # Upload file to S3
    
    - name: Upload template to S3
      run: |
        aws s3 cp template/cf-template.yml s3://my-artifact-storage/cf-template/
