name: Upload Template to S3

on:
  push:
    branches:
      - master

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configure AWS CLI
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Upload template to S3
      - name: Upload Template to S3
        run: |
          aws s3 cp templates/cf-template.yml s3://${{ secrets.my-artifact-storage/cf-artifacts }}/
